In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

records = []

years = list(range(2010, 2019))
months = list(range(1, 13))
weeks = list(range(0, 5))

for year in years:
    for month in months:
        for week in weeks:
            
            # HTML 받아오기
            response = requests.get("https://workey.codeit.kr/ratings/index?year={}&month={}&weekIndex={}".format(year, month, week))
            # BeautifulSoup 받아 오기 
            soup = BeautifulSoup(response.text, 'html.parser')
            
            if len(soup.select(".row")) > 1:
                period_select = soup.select("#weekSelectBox > option")[0]
                rank_select = soup.select("tr.row > td.rank")
                channel_select = soup.select("tr.row > td.channel")
                program_select = soup.select("tr.row > td.program")
                rating_select = soup.select("tr.row > td.percent")
                
                for i in range(len(rank_select)):
                    record = []
                    record.append(period_select.text)
                    record.append(rank_select[i].text)
                    record.append(channel_select[i].text)
                    record.append(program_select[i].text)
                    record.append(rating_select[i].text)
                    records.append(record)
            else:
                continue
                    
# 코드를 작성하세요.
df = pd.DataFrame(data = records, columns = ["period", "rank", "channel", "program", "rating"])

# 결과 출력
df.head()

                    period rank channel        program rating
0  2009.12.28 ~ 2010.01.03    1    KBS2  주말연속극(수상한삼형제)   33.4
1  2009.12.28 ~ 2010.01.03    2    KBS1  일일연속극(다함께차차차)   33.1
2  2009.12.28 ~ 2010.01.03    3    KBS2          해피선데이   27.1
3  2009.12.28 ~ 2010.01.03    4     MBC      MBC연기대상2부   24.4
4  2009.12.28 ~ 2010.01.03    5     SBS   주말극장(천만번사랑해)   24.2